name: TruffleHog Scan

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS Scan
        uses: trufflesecurity/trufflehog@v3.90.6
        with:
          path: ./
          base: ${{ github.event.before }}
          head: ${{ github.event.after }}
